### ISSUE TITLE
Poor results

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/BroadNibber#2]
![screen shot 2015-06-26 at 11 18 48 am](https://cloud.githubusercontent.com/assets/1271897/8374360/137d56ee-1bf5-11e5-9f0b-8f876ef5c200.png)
![screen shot 2015-06-26 at 11 19 06 am](https://cloud.githubusercontent.com/assets/1271897/8374361/137e03b4-1bf5-11e5-8f6f-a64f7b3011b7.png)

**Comment by mekkablue** [comment]
Which Settings?

**Comment by weiweihuanghuang** [comment]
![screen shot 2015-06-26 at 1 45 20 pm](https://cloud.githubusercontent.com/assets/1271897/8376625/8548487e-1c09-11e5-9dc9-ca7f8d4a09dc.png)

**Comment by mekkablue** [comment]
These values are to large for the curves. Too much for the Curve Offset algorithm. Not much I can do about it now. Sorry.

**Comment by Nevu** [comment]
Hi, 

I tried to use BroadNibber for custom parameter - copy and paste, then clean up, and export. But I got the following message ans Im confused: 
_processLayerWithValues: 'BroadNibber' object has no attribute 'offsetCurveFilter'_

**Comment by mekkablue** [comment]
Which version of Glyphs? And which version of the plugin?

**Comment by Nevu** [comment]
Oh yes, sorry: 
G2 - ; 2.1.1 769
Plugins ( Latest with the AddOn-Manager) Broadnibber - V. 23 Feb

**Comment by mekkablue** [comment]
should be fixed now
