### ISSUE TITLE
'LayerSelectionProxy'

### ISSUE THREAD

**Issue by fizzybubbele** [mekkablue/BroadNibber#3]
Hi Mekkablue,

there may be a issue with the plugin, i can't get any results – the path simply doesn't move.
I get this message from the macro planel: 
Filter Broad Nibber: process_: 'LayerSelectionProxy' object is not callable

Thanks for your help!

**Comment by mekkablue** [comment]
Just uploaded a compatibility update for Glyphs 2.2+
