### ISSUE TITLE
Erroneous Update Notice

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/BroadNibber#5]
I've been getting a repetitive update notice for BroadNibber -- even though I already had 1.1.4 installed. Yesterday I relented and updated it again. Today the message is back. I'm using G2.2.2 [823], OS X 10.11.1.

Screenshot here:
![erroneous update notification](https://cloud.githubusercontent.com/assets/2348503/11173638/868a06ec-8bde-11e5-80e8-64afebbc754a.png)

**Comment by mekkablue** [comment]
Version 1.1.5 should fix this. Thx for reporting.
