### ISSUE TITLE
non-continuous outlines

### ISSUE THREAD

**Issue by opentype-RH** [mekkablue/BroadNibber#7]
![bildschirmfoto 2018-02-22 um 15 19 06](https://user-images.githubusercontent.com/29516339/36543447-13268060-17e4-11e8-8cf3-de6b716b62d4.png)

Sometimes I am getting this problem. The generated outline path has two corner points (slightly set apart) on both sides of the original stroke, which creates an ugly dent in the path. Any idea what is causing this and how it could be fixed?

**Comment by mekkablue** [comment]
Probably a rounding problem. Not much I can do about it from here, I am afraid. Georg would have to change the Offset algorithms for that.

You could try and rearrange the segments in a way that no segment bends too much (<100°).
