### ISSUE TITLE
exclude: in custom parameter not working like other filters

### ISSUE THREAD

**Issue by larshoie** [mekkablue/BroadNibber#8]
Hi, I'm using this PreFilter in one instance OffsetCurve;4;4;1;auto;keep;exclude:_dot and that works as expected. 

In another I use broadnibber with these settings: 
```
BroadNibber;width:4.0;height:100.0;angle:30.0;exclude:_dot
```
And I get this error: 
```
There was an error in BroadNibber's filter() method when called through a Custom Parameter upon font export. Check your Macro window output.
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 528, in processFont_withArguments_
TypeError: Need 0 arguments, got 1
```

I'm using Glyphs 3.0.5 (3124) running on apple silicon

**Comment by mekkablue** [comment]
This was a bug in Glyphs. Fixed in the upcoming beta.
